package myerror

const (
	INVALID_BODY         = -1
	SUCCESS              = 0
	USER_NOT_FOUND       = 1
	PERMISSION_DENIED    = 2
	DUPLICATED_NAME      = 3
	TOKEN_EMPTY          = 5
	TOKEN_INVALID        = 6
	TOKEN_EXPIRED        = 7
	INVALID_PARAM        = 8
	ENTITY_NOT_FOUND     = 9
	USER_HAS_EXISTED     = 10
	USER_NOT_IN_ENTITY   = 11
	NAME_CANNOT_EMPTY    = 12
	DEPARTMENT_NOT_FOUND = 13
)
